export const CascaderTree = {
  code: 200,
  message: '操作成功',
  success: true,
  data: [
    {
      id: '1779763845609172993',
      dictCode: 'books',
      dictNameCnj: '书刊类',
      dictNameCnf: '书刊类',
      dictNameEn: 'books',
      dictType: 'PTBT',
      dictTypeName: '产品大类',
      extend1: '1',
      extend2: null,
      extend3: null,
      searchCode: null,
      parentId: '1653934830988918785',
      dictStatus: 0,
      remark: '生产主计划',
      tenantId: '1',
      createName: '麦永荣',
      createDate: '2024-04-15T06:47:47',
      nodeBits: 5,
      openClose: null,
      children: [
        {
          id: '1653235766356233294',
          dictCode: '05.HAND',
          dictNameCnj: '手工',
          dictNameCnf: '手工类',
          dictNameEn: '05.Hand',
          dictType: 'PTBT',
          dictTypeName: '产品大类',
          extend1: '1',
          extend2: null,
          extend3: null,
          searchCode: null,
          parentId: '1779763845609172993',
          dictStatus: 0,
          remark: null,
          tenantId: '1',
          createName: 'user5',
          createDate: '2023-05-04T01:30:15',
          nodeBits: 15,
          openClose: null,
          children: [
            {
              id: '1759743712950104065',
              dictCode: 'HAND01',
              dictNameCnj: '板纸书',
              dictNameCnf: '板纸书',
              dictNameEn: 'board book',
              dictType: 'PTBT',
              dictTypeName: '产品大类',
              extend1: '2',
              extend2: null,
              extend3: null,
              searchCode: null,
              parentId: '1653235766356233294',
              dictStatus: 0,
              remark: null,
              tenantId: '1',
              createName: '麦永荣',
              createDate: '2024-02-20T00:55:01',
              nodeBits: 0,
              openClose: null,
              children: null,
            },
          ],
        },
        {
          id: '1653935766356233214',
          dictCode: '04.CASE',
          dictNameCnj: '精装',
          dictNameCnf: '精装',
          dictNameEn: '04.Case bound',
          dictType: 'PTBT',
          dictTypeName: '产品大类',
          extend1: '1',
          extend2: null,
          extend3: null,
          searchCode: null,
          parentId: '1779763845609172993',
          dictStatus: 0,
          remark: null,
          tenantId: '1',
          createName: 'user5',
          createDate: '2023-05-04T01:30:15',
          nodeBits: 15,
          openClose: null,
          children: [
            {
              id: '1658412425449115650',
              dictCode: 'CASE07',
              dictNameCnj: '软面自衬方脊精装',
              dictNameCnf: '軟面自襯方脊精裝',
              dictNameEn: 'PS00011',
              dictType: 'PTBT',
              dictTypeName: '产品大类',
              extend1: '2',
              extend2: null,
              extend3: null,
              searchCode: null,
              parentId: '1653935766356233214',
              dictStatus: 0,
              remark: null,
              tenantId: '1',
              createName: 'user5',
              createDate: '2023-05-16T10:01:41',
              nodeBits: 0,
              openClose: null,
              children: null,
            },
            {
              id: '1658403086575407105',
              dictCode: 'CASE04',
              dictNameCnj: '硬面自衬圆脊精装',
              dictNameCnf: '硬面自襯圓脊精裝',
              dictNameEn: 'PS00008',
              dictType: 'PTBT',
              dictTypeName: '产品大类',
              extend1: '2',
              extend2: null,
              extend3: null,
              searchCode: null,
              parentId: '1653935766356233214',
              dictStatus: 0,
              remark: null,
              tenantId: '1',
              createName: 'user5',
              createDate: '2023-05-16T09:24:20',
              nodeBits: 0,
              openClose: null,
              children: null,
            },
            {
              id: '1658412276312248321',
              dictCode: 'CASE06',
              dictNameCnj: '软面圆脊精装',
              dictNameCnf: '軟面圓脊精裝',
              dictNameEn: 'PS00010',
              dictType: 'PTBT',
              dictTypeName: '产品大类',
              extend1: '2',
              extend2: null,
              extend3: null,
              searchCode: null,
              parentId: '1653935766356233214',
              dictStatus: 0,
              remark: null,
              tenantId: '1',
              createName: 'user5',
              createDate: '2023-05-16T10:00:55',
              nodeBits: 0,
              openClose: null,
              children: null,
            },
            {
              id: '1653936522476224514',
              dictCode: 'CASE02',
              dictNameCnj: '硬面圆脊精装',
              dictNameCnf: '硬面圆脊精装',
              dictNameEn: 'Round Ridge Decoration',
              dictType: 'PTBT',
              dictTypeName: '产品大类',
              extend1: '2',
              extend2: null,
              extend3: null,
              searchCode: null,
              parentId: '1653935766356233214',
              dictStatus: 0,
              remark: null,
              tenantId: '1',
              createName: 'user5',
              createDate: '2023-05-04T01:35:02',
              nodeBits: 0,
              openClose: null,
              children: null,
            },
            {
              id: '1658402649486987266',
              dictCode: 'CASE03',
              dictNameCnj: '硬面自衬方脊精装',
              dictNameCnf: '硬面自襯方脊精裝',
              dictNameEn: 'PS00007',
              dictType: 'PTBT',
              dictTypeName: '产品大类',
              extend1: '2',
              extend2: null,
              extend3: null,
              searchCode: null,
              parentId: '1653935766356233214',
              dictStatus: 0,
              remark: null,
              tenantId: '1',
              createName: 'user5',
              createDate: '2023-05-16T09:22:49',
              nodeBits: 0,
              openClose: null,
              children: null,
            },
            {
              id: '1658412594152411137',
              dictCode: 'CASE08',
              dictNameCnj: '软面自衬圆脊精装',
              dictNameCnf: '軟面自襯圓脊精裝',
              dictNameEn: 'PS00012',
              dictType: 'PTBT',
              dictTypeName: '产品大类',
              extend1: '2',
              extend2: null,
              extend3: null,
              searchCode: null,
              parentId: '1653935766356233214',
              dictStatus: 0,
              remark: null,
              tenantId: '1',
              createName: 'user5',
              createDate: '2023-05-16T10:02:18',
              nodeBits: 0,
              openClose: null,
              children: null,
            },
            {
              id: '1653936819378421761',
              dictCode: 'CASE01',
              dictNameCnj: '硬面方脊精装',
              dictNameCnf: '硬面方脊精装',
              dictNameEn: 'Square Spine Fine Decoration',
              dictType: 'PTBT',
              dictTypeName: '产品大类',
              extend1: '2',
              extend2: null,
              extend3: null,
              searchCode: null,
              parentId: '1653935766356233214',
              dictStatus: 0,
              remark: null,
              tenantId: '1',
              createName: 'user5',
              createDate: '2023-05-04T01:36:25',
              nodeBits: 0,
              openClose: null,
              children: null,
            },
            {
              id: '1658412099065155585',
              dictCode: 'CASE05',
              dictNameCnj: '软面方脊精装',
              dictNameCnf: '軟面方脊精裝',
              dictNameEn: 'PS00009',
              dictType: 'PTBT',
              dictTypeName: '产品大类',
              extend1: '2',
              extend2: null,
              extend3: null,
              searchCode: null,
              parentId: '1653935766356233214',
              dictStatus: 0,
              remark: null,
              tenantId: '1',
              createName: 'user5',
              createDate: '2023-05-16T09:59:51',
              nodeBits: 0,
              openClose: null,
              children: null,
            },
          ],
        },
        {
          id: '1653935766956244914',
          dictCode: '01.SADDLE',
          dictNameCnj: '骑马订',
          dictNameCnf: '骑马订',
          dictNameEn: '01.Saddle',
          dictType: 'PTBT',
          dictTypeName: '产品大类',
          extend1: '1',
          extend2: null,
          extend3: null,
          searchCode: null,
          parentId: '1779763845609172993',
          dictStatus: 0,
          remark: null,
          tenantId: '1',
          createName: 'user5',
          createDate: '2023-05-04T01:30:15',
          nodeBits: 15,
          openClose: null,
          children: [
            {
              id: '1656858307496607746',
              dictCode: 'SADDLE01',
              dictNameCnj: '骑马钉',
              dictNameCnf: '騎馬釘',
              dictNameEn: 'Saddle Stitch',
              dictType: 'PTBT',
              dictTypeName: '产品大类',
              extend1: '2',
              extend2: '',
              extend3: '',
              searchCode: null,
              parentId: '1653935766956244914',
              dictStatus: 0,
              remark: null,
              tenantId: '1',
              createName: 'user5',
              createDate: '2023-05-12T03:03:01',
              nodeBits: 2,
              openClose: null,
              children: null,
            },
          ],
        },
        {
          id: '1653235166356243264',
          dictCode: '06.OTHER',
          dictNameCnj: '其他',
          dictNameCnf: '其他',
          dictNameEn: '06.Other books',
          dictType: 'PTBT',
          dictTypeName: '产品大类',
          extend1: '1',
          extend2: null,
          extend3: null,
          searchCode: null,
          parentId: '1779763845609172993',
          dictStatus: 0,
          remark: null,
          tenantId: '1',
          createName: 'user5',
          createDate: '2023-05-04T01:30:15',
          nodeBits: 15,
          openClose: null,
          children: null,
        },
        {
          id: '1653935766956233114',
          dictCode: '03.LIMP',
          dictNameCnj: '平装',
          dictNameCnf: '平装',
          dictNameEn: '03.Limp',
          dictType: 'PTBT',
          dictTypeName: '产品大类',
          extend1: '1',
          extend2: null,
          extend3: null,
          searchCode: null,
          parentId: '1779763845609172993',
          dictStatus: 0,
          remark: null,
          tenantId: '1',
          createName: 'user5',
          createDate: '2023-05-04T01:30:15',
          nodeBits: 15,
          openClose: null,
          children: [
            {
              id: '1658402262243676161',
              dictCode: 'LIMP01',
              dictNameCnj: '串线平装',
              dictNameCnf: '串線平裝',
              dictNameEn: 'PS00004',
              dictType: 'PTBT',
              dictTypeName: '产品大类',
              extend1: '2',
              extend2: null,
              extend3: null,
              searchCode: null,
              parentId: '1653935766956233114',
              dictStatus: 0,
              remark: null,
              tenantId: '1',
              createName: 'user5',
              createDate: '2023-05-16T09:20:15',
              nodeBits: 0,
              openClose: null,
              children: null,
            },
          ],
        },
        {
          id: '1653935766956244114',
          dictCode: '02.NOTCH',
          dictNameCnj: '胶装',
          dictNameCnf: '胶装',
          dictNameEn: '02.Notch',
          dictType: 'PTBT',
          dictTypeName: '产品大类',
          extend1: '1',
          extend2: null,
          extend3: null,
          searchCode: null,
          parentId: '1779763845609172993',
          dictStatus: 0,
          remark: null,
          tenantId: '1',
          createName: 'user5',
          createDate: '2023-05-04T01:30:15',
          nodeBits: 15,
          openClose: null,
          children: [
            {
              id: '1658398065355984897',
              dictCode: 'NOTCH02',
              dictNameCnj: '无线磨脊胶装',
              dictNameCnf: '無線磨脊膠裝',
              dictNameEn: 'PS00003',
              dictType: 'PTBT',
              dictTypeName: '产品大类',
              extend1: '2',
              extend2: null,
              extend3: null,
              searchCode: null,
              parentId: '1653935766956244114',
              dictStatus: 0,
              remark: null,
              tenantId: '1',
              createName: 'user5',
              createDate: '2023-05-16T08:58:00',
              nodeBits: 0,
              openClose: null,
              children: null,
            },
            {
              id: '1658412760137797634',
              dictCode: 'NOTCH03',
              dictNameCnj: '串线胶装',
              dictNameCnf: '串線膠裝',
              dictNameEn: 'PS00013',
              dictType: 'PTBT',
              dictTypeName: '产品大类',
              extend1: '2',
              extend2: null,
              extend3: null,
              searchCode: null,
              parentId: '1653935766956244114',
              dictStatus: 0,
              remark: null,
              tenantId: '1',
              createName: 'user5',
              createDate: '2023-05-16T10:03:00',
              nodeBits: 0,
              openClose: null,
              children: null,
            },
            {
              id: '1656859077029756929',
              dictCode: 'NOTCH01',
              dictNameCnj: '无线通气胶装',
              dictNameCnf: '無線通氣膠裝',
              dictNameEn: 'Wireless Ventilation Adhesive Installation',
              dictType: 'PTBT',
              dictTypeName: '产品大类',
              extend1: '2',
              extend2: null,
              extend3: null,
              searchCode: null,
              parentId: '1653935766956244114',
              dictStatus: 0,
              remark: null,
              tenantId: '1',
              createName: 'user5',
              createDate: '2023-05-12T03:07:54',
              nodeBits: 2,
              openClose: null,
              children: null,
            },
            {
              id: '1658412920767057922',
              dictCode: 'NOTCH04',
              dictNameCnj: '无线通气胶装含折翼',
              dictNameCnf: '無線通氣膠裝含折翼',
              dictNameEn: 'PS00014',
              dictType: 'PTBT',
              dictTypeName: '产品大类',
              extend1: '2',
              extend2: null,
              extend3: null,
              searchCode: null,
              parentId: '1653935766956244114',
              dictStatus: 0,
              remark: null,
              tenantId: '1',
              createName: 'user5',
              createDate: '2023-05-16T10:03:30',
              nodeBits: 0,
              openClose: null,
              children: null,
            },
            {
              id: '1658413073125150721',
              dictCode: 'NOTCH05',
              dictNameCnj: '无线磨脊胶装含折翼',
              dictNameCnf: '無線磨脊膠裝含折翼',
              dictNameEn: 'PS00015',
              dictType: 'PTBT',
              dictTypeName: '产品大类',
              extend1: '2',
              extend2: null,
              extend3: null,
              searchCode: null,
              parentId: '1653935766956244114',
              dictStatus: 0,
              remark: null,
              tenantId: '1',
              createName: 'user5',
              createDate: '2023-05-16T10:04:13',
              nodeBits: 0,
              openClose: null,
              children: null,
            },
          ],
        },
      ],
    },
    {
      id: '1779763845609172994',
      dictCode: 'packing',
      dictNameCnj: '包装类',
      dictNameCnf: '包装类',
      dictNameEn: 'packing',
      dictType: 'PTBT',
      dictTypeName: '产品大类',
      extend1: '0',
      extend2: null,
      extend3: null,
      searchCode: null,
      parentId: '1653934830988918785',
      dictStatus: 0,
      remark: '生产主计划',
      tenantId: '1',
      createName: '麦永荣',
      createDate: '2024-04-15T06:47:47',
      nodeBits: 5,
      openClose: null,
      children: null,
    },
    {
      id: '1793556417335443458',
      dictCode: 'ENVELOPE-EXPRESS',
      dictNameCnj: '信封-快递封',
      dictNameCnf: '信封-快递封',
      dictNameEn: 'ENVELOPE-EXPRESS',
      dictType: 'PTBT',
      dictTypeName: '产品大类',
      extend1: '1',
      extend2: null,
      extend3: null,
      searchCode: null,
      parentId: '1653934830988918785',
      dictStatus: 0,
      remark: null,
      tenantId: '1',
      createName: '刘利',
      createDate: '2024-05-23T08:13:36',
      nodeBits: 2,
      openClose: null,
      children: [
        {
          id: '1793556760253349890',
          dictCode: 'ENVELOPECN',
          dictNameCnj: '中式信封',
          dictNameCnf: '中式信封',
          dictNameEn: 'chinese envelope',
          dictType: 'PTBT',
          dictTypeName: '产品大类',
          extend1: '2',
          extend2: null,
          extend3: null,
          searchCode: null,
          parentId: '1793556417335443458',
          dictStatus: 0,
          remark: null,
          tenantId: '1',
          createName: '刘利',
          createDate: '2024-05-23T08:16:11',
          nodeBits: 0,
          openClose: null,
          children: null,
        },
        {
          id: '1795371720423948290',
          dictCode: 'ENVELOPEEN',
          dictNameCnj: '西式信封',
          dictNameCnf: '西式信封',
          dictNameEn: '西式信封',
          dictType: 'PTBT',
          dictTypeName: '产品大类',
          extend1: '2',
          extend2: null,
          extend3: null,
          searchCode: null,
          parentId: '1793556417335443458',
          dictStatus: 0,
          remark: null,
          tenantId: '1',
          createName: '刘利',
          createDate: '2024-05-28T08:28:37',
          nodeBits: 0,
          openClose: null,
          children: null,
        },
        {
          id: '1795716067472359426',
          dictCode: 'ENVELOPEEX',
          dictNameCnj: '快递封',
          dictNameCnf: '快递封',
          dictNameEn: 'express delivery seal',
          dictType: 'PTBT',
          dictTypeName: '产品大类',
          extend1: '2',
          extend2: null,
          extend3: null,
          searchCode: null,
          parentId: '1793556417335443458',
          dictStatus: 0,
          remark: null,
          tenantId: '1',
          createName: '刘利',
          createDate: '2024-05-29T07:16:40',
          nodeBits: 0,
          openClose: null,
          children: null,
        },
      ],
    },
    {
      id: '1895708527598258969',
      dictCode: 'PAPERBAG',
      dictNameCnj: '纸袋',
      dictNameCnf: '纸袋',
      dictNameEn: 'PAPERBAG',
      dictType: 'PTBT',
      dictTypeName: '产品大类',
      extend1: '1',
      extend2: null,
      extend3: null,
      searchCode: null,
      parentId: '1653934830988918785',
      dictStatus: 0,
      remark: null,
      tenantId: '1',
      createName: '刘利',
      createDate: '2024-05-23T08:13:36',
      nodeBits: 2,
      openClose: null,
      children: [
        {
          id: '189570852759825897',
          dictCode: 'PAPERBAG',
          dictNameCnj: '纸袋',
          dictNameCnf: '纸袋',
          dictNameEn: 'PAPERBAG',
          dictType: 'PTBT',
          dictTypeName: '产品大类',
          extend1: '2',
          extend2: null,
          extend3: null,
          searchCode: null,
          parentId: '1895708527598258969',
          dictStatus: 0,
          remark: null,
          tenantId: '1',
          createName: '刘利',
          createDate: '2024-05-23T08:16:11',
          nodeBits: 0,
          openClose: null,
          children: null,
        },
      ],
    },
    {
      id: '1895708527598258961',
      dictCode: 'LABEL',
      dictNameCnj: '标签',
      dictNameCnf: '标签',
      dictNameEn: 'LABEL',
      dictType: 'PTBT',
      dictTypeName: '产品大类',
      extend1: '1',
      extend2: null,
      extend3: null,
      searchCode: null,
      parentId: '1653934830988918785',
      dictStatus: 0,
      remark: null,
      tenantId: '1',
      createName: '刘利',
      createDate: '2024-05-23T08:13:36',
      nodeBits: 2,
      openClose: null,
      children: [
        {
          id: '1895708527598258962',
          dictCode: 'COMMONLABEL',
          dictNameCnj: '普通标签',
          dictNameCnf: '普通标签',
          dictNameEn: 'COMMONLABEL',
          dictType: 'PTBT',
          dictTypeName: '产品大类',
          extend1: '2',
          extend2: null,
          extend3: null,
          searchCode: null,
          parentId: '1895708527598258961',
          dictStatus: 0,
          remark: null,
          tenantId: '1',
          createName: '刘利',
          createDate: '2024-05-23T08:16:11',
          nodeBits: 0,
          openClose: null,
          children: null,
        },
      ],
    },
  ],
}
